-- 사용자 DB 생성
CREATE DATABASE IF NOT EXISTS user_service;
USE user_service;

-- 사용자 테이블
CREATE TABLE users (
    user_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '사용자 ID',
    email VARCHAR(255) NOT NULL UNIQUE COMMENT '이메일 (로그인용)',
    password VARCHAR(255) NOT NULL COMMENT '비밀번호 (해시 저장)',
    name VARCHAR(100) NOT NULL COMMENT '사용자 이름',
    phone VARCHAR(20) DEFAULT NULL COMMENT '연락처',
    role VARCHAR(20) NOT NULL DEFAULT 'USER' COMMENT '사용자 권한 (USER, ADMIN)',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '사용자 상태 (ACTIVE, INACTIVE, SUSPENDED)',
    grade VARCHAR(20) NOT NULL DEFAULT 'NORMAL' COMMENT '회원 등급 (NORMAL, VIP 등)',
    points BIGINT NOT NULL DEFAULT 0 COMMENT '포인트',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP 
        ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
  COMMENT='쇼핑몰 사용자 정보 테이블';

-- 이벤트 메시지 테이블
CREATE TABLE outbox (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '이벤트 ID',
    aggregate_type VARCHAR(255) NOT NULL COMMENT '이벤트 소스 타입',
    aggregate_id VARCHAR(255) NOT NULL COMMENT '이벤트 소스 ID',
    event_type VARCHAR(255) NOT NULL COMMENT '이벤트 타입',
    payload TEXT NOT NULL COMMENT '이벤트 페이로드',
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT '이벤트 상태 (PENDING, PUBLISHED, FAILED)',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    published_at TIMESTAMP NULL COMMENT '발행 일시',
    INDEX idx_event_type_status (event_type, status) COMMENT '이벤트 타입과 상태 인덱스'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='이벤트 메시지 테이블';