-- 사용자 테이블
CREATE TABLE user (
    user_id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '사용자 ID',
    email VARCHAR(255) NOT NULL UNIQUE COMMENT '이메일 (로그인용)',
    password VARCHAR(255) NOT NULL COMMENT '비밀번호 (해시 저장)',
    name VARCHAR(100) NOT NULL COMMENT '사용자 이름',
    phone VARCHAR(20) COMMENT '연락처',
    
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '사용자 상태 (ACTIVE, INACTIVE, SUSPENDED)',
    grade VARCHAR(20) DEFAULT 'NORMAL' COMMENT '회원 등급 (NORMAL, VIP 등)',
    points BIGINT NOT NULL DEFAULT 0 COMMENT '포인트',
    
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP 
        ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시'
) COMMENT='쇼핑몰 사용자 정보 테이블';